
###View Source Demo Page ( Sandbox ) 



####Example #1

To create a link that when clicked shows the source to a file, add the '.view_source' class to the links:

>You may use either the url to the file, or the relative path to the file itself.

*Using the url*  

    [Show Source{: .view_source}](/viewsource/demo/)

 
    
*Using the relative path*    

        [Show Source{: .view_source}](/plugins/Forms/content/phbc-form-examples/getting-started.php)
        
*Demo*

Click the 'Show Source' link below, and if you are viewing this page with the ViewSource plugin activated, you'll see the source of this page appear below the link.

[Show Source{: .view_source}](/plugins/Forms/content/phbc-form-examples/getting-started.php)     

>You may only link to the same source file once on a page. Linking to the same source file multiple times on the same page will result in 
unexpected behavior.
{: .alert .alert-info}


####Example #2

To see what the ViewSource plugin will add to every content element, click the 'src' link at the end of this page. A 'content element' is any part of the web page that gets its content from a standalone file that is not part of the template or generated by a plugin. 

Lorem ipsum dolor sit amet, homero feugiat rationibus ei has, no animal scripta iracundia vis. At vel clita consequat. At voluptatibus comprehensam mei, est ea docendi adipiscing. An agam pericula urbanitas usu, cu sit aperiri virtute fuisset, cu nec postea animal facilisi.

1. Point 1
2. Point 2

[my button{: .btn .btn-success}](#)

Cu vim quod quot. Ut est tollit voluptaria, cu legendos tacimates cum. Vel te doming rationibus incorrupte. Eos novum solet expetendis ne. Detraxit concludaturque usu ne.

Perfecto consulatu aliquando ei nec, ad sale singulis pri. Vim te causae viderer oportere. Eos legere democritum intellegam an, ad abhorreant quaerendum concludaturque ius. Eu eirmod intellegam his, an tollit laoreet repudiare nam.